name: Deploy

on: 
  workflow_dispatch:
    inputs: {}
  release:
    types:
      - published


jobs:
  deploy:
    name: Deploy Web Vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: rc

      - name: Install and Build
        run: |
          npm install
          npm run dist

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925  # 2.5.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
