name: Deploy

on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version <X.X.X>"
        required: true
  release:
    types:
      - published


jobs:
  deploy:
    name: Deploy Web Vault
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: rc

      - name: Install and Build
        run: |
          npm install
          npm run dist

      - name: Get release version
        id: release-version
        run:
          if [[ ${{ github.event_name }} == "release" ]]; then
              echo "::set-output name=version::${{ github.event.release.tag_name }}"
          else
              echo "::set-output name=version::${{ github.event.inputs.release_version }}"
          fi

      - name: Deploy GitHub Pages
        uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925  # 2.5.0
        with:
          target_branch: gh-pages
          build_dir: build
          keep_history: true
          commit_message: "Deploying ${{ steps.release-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
